# Generated by Django 4.2 on 2023-05-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_App", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
    ]
